version: '3'
services:
  stock_manager:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stock_manager
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/mysql
